### ISSUE TITLE
Build failure with fsnotify 0.3.x

### ISSUE THREAD

**Issue by bergmark** [kelemzol/watch#3]
```
Preprocessing library for fswatch-0.1.0.3..
Building library for fswatch-0.1.0.3..
[1 of 3] Compiling System.FSWatch.Repr ( src/System/FSWatch/Repr.hs, dist/build/System/FSWatch/Repr.o )
[2 of 3] Compiling System.FSWatch   ( src/System/FSWatch.hs, dist/build/System/FSWatch.o )

src/System/FSWatch.hs:166:11: error:
    • The constructor ‘Added’ should have 3 arguments, but has been given 2
    • In the pattern: Added str _
      In an equation for ‘event2PE’: event2PE (Added str _) = Add str
    |
166 | event2PE (Added str _) = Add str
    |
```

**Comment by simonmichael** [comment]
I made hledger 1.10 depend on fsnotify 0.3.0.1, but I see fsnotify 0.3 is being kept out of stackage, I think mainly to keep fswatch building. @kelemzol do you think fswatch could be updated so that fsnotify 0.3 can go in ? 

I think an LTS release is imminent, so if this won't happen before then I'd like to know, so I can revert hledger to old fsnotify in time to get into the LTS.

**Comment by simonmichael** [comment]
And of course ideally I'd like to stay with the newer possibly more robust fsnotify. Another option would be to drop fswatch from stackage nightly. I think nothing else in stackage depends on it, and only one package on hackage does.

**Comment by kelemzol** [comment]
Now its worked with fsnotify 0.3.x and nightly stackage
